image:
  repository: ghcr.io/joshuaavalon/cloudflare-ddns
  pullPolicy: IfNotPresent
  tag: latest@sha256:3fbd3f66433fe621f3b9a692f1880e6d3b65464bd79b7daabc723b2added07a6

securityContext:
  container:
    runAsNonRoot: false
    readOnlyRootFilesystem: false
    runAsUser: 0
    runAsGroup: 0

cloudflareddns:
  user: your.cf.email@example.com
  api_token: ""
  api_key: ""
  api_token_zone: ""
  interval: 300
  detect_mode: dig-whoami.cloudflare
  detect_override: ""
  log_level: 3
  host_zone_record: []

service:
  main:
    enabled: false
    ports:
      main:
        enabled: false

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              enabled: false
            readiness:
              enabled: false
            startup:
              enabled: false
          envFrom:
            - secretRef:
                name: "secret"
          env: {}

persistence:
  config:
    enabled: true
    mountPath: /config

portal:
  open:
    enabled: false