apiVersion: v2
appVersion: 4.5.0
dependencies:
  - name: common
    repository: file://../../../library/common/2023.01.01
    version: 2023.01.01
description: qBittorrent is a cross-platform free and open-source BitTorrent client.
home: https://www.qbittorrent.org/
icon: https://github.com/linuxserver/docker-templates/raw/master/linuxserver.io/img/qbittorrent-icon.png
keywords:
  - storage
  - torrent
kubeVersion: ">=1.16.0-0"
name: qbittorent
sources:
  - https://github.com/qbittorrent/qBittorrent
type: application
version: 1.0.0
