image:
  repository: bitnami/openldap
  pullPolicy: IfNotPresent
  tag: 2.5.14

securityContext:
  readOnlyRootFilesystem: false
  runAsNonRoot: false

podSecurityContext:
  runAsUser: 0
  runAsGroup: 0

controller:
  type: statefulset
  replicas: 1
  strategy: RollingUpdate
  rollingUpdate:
    unavailable: 1
    surge:
    partition:
  revisionHistoryLimit: 3

persistence:
  varrun:
    enabled: false

service:
  main:
    ports:
      main:
        port: 389
        targetPort: 389
  ldaps:
    enabled: true
    ports:
      ldaps:
        enabled: true
        port: 636
        targetPort: 636

secretEnv:
  LDAP_ADMIN_PASSWORD: "ldapadmin"
  LDAP_CONFIG_PASSWORD: "changeme"
  LDAP_READONLY_USER_USERNAME: "readonly"
  LDAP_READONLY_USER_PASSWORD: "readonly"

env:
  LDAP_LOG_LEVEL: 256
  LDAP_ORGANISATION: "Example Inc."
  LDAP_DOMAIN: "example.org"
  LDAP_READONLY_USER: false
  LDAP_RFC2307BIS_SCHEMA: false
  LDAP_BACKEND: "mdb"
  LDAP_TLS: true
  LDAP_TLS_ENFORCE: false
  LDAP_TLS_VERIFY_CLIENT: "never"
  LDAP_TLS_PROTOCOL_MIN: "3.0"
  LDAP_TLS_CIPHER_SUITE: "NORMAL"
  LDAP_TLS_REQCERT: "never"
  CONTAINER_LOG_LEVEL: 4
  KEEP_EXISTING_CONFIG: false
  LDAP_REMOVE_CONFIG_AFTER_SETUP: true
  LDAP_SSL_HELPER_PREFIX: "ldap"
  LDAP_BASE_DN: ""

replication:
  enabled: false
  clusterName: "cluster.local"
  retry: 60
  timeout: 1
  interval: 00:00:00:10
  starttls: "critical"
  tls_reqcert: "never"

envFrom:
  - configMapRef:
      name: openldapconfig

volumeClaimTemplates:
  data:
    enabled: true
    mountPath: "/var/lib/ldap/"
  slapd:
    enabled: true
    mountPath: "/etc/ldap/slapd.d/"

portal:
  enabled: false