apiVersion: v2
appVersion: "2.23.0"
dependencies:
  - name: common
    repository: file://../../../library/common/2023.01.01
    version: 2023.01.01
deprecated: false
description: Filebrowser provides a file managing interface within a specified directory
icon: https://github.com/filebrowser/filebrowser/blob/73ccbe912fc1848957d8b2f6bbe5243804769d85/frontend/public/img/logo.svg
keywords:
  - filebrowser
kubeVersion: ">=1.16.0-0"
name: filebrowser
sources:
  - https://github.com/filebrowser/filebrowser
  - https://filebrowser.org/cli/filebrowser
  - https://hub.docker.com/r/filebrowser/filebrowser
type: application
version: 1.0.0