image:
  repository: https://github.com/filebrowser/filebrowser
  pullPolicy: IfNotPresent
  tag: 2.23.0

service:
  main:
    ports:
      main:
        port: 10187

env:
  FB_ADDRESS: ""
  FB_BASEURL: ""
  FB_DATABASE: "/database/filebrowser.db"
  FB_CONFIG: "/config/filebrowser.json"
  FB_ROOT: "/data"
  FB_PORT: "{{ .Values.service.main.ports.main.port }}"

persistence:
  config:
    enabled: true
    mountPath: "/config"
  database:
    enabled: true
    mountPath: "/database"
  data:
    enabled: true
    mountPath: "/data"

portal:
  enabled: true