image:
  repository: keycloak/keycloak
  pullPolicy: IfNotPresent
  tag: 21.1@sha256:cee8a0b343993b699a3d3eeb90e0b1eca2fa19285a413200af9785db8b00dcd7

securityContext:
  container:
    readOnlyRootFilesystem: false

service:
  main:
    ports:
      main:
        protocol: http
        targetPort: 9117
        port: 8080

workload:
  main:
    podSpec:
      containers:
        main:
          probes:
            liveness:
              path: "/"
            readiness:
              path: "/"
            startup:
              path: "/"

persistence:
  config:
    enabled: true
    mountPath: "/config"

portal:
  open:
    enabled: true